### ISSUE TITLE
Error in Heroku Deployment

### ISSUE THREAD

**Issue by Rocky2242** [viperadnan-git/google-drive-telegram-bot#60]
i am able to run in local but not in heroku ,heroku logs

2021-03-19 10:38:23,937 - __main__ - INFO - Starting Bot !
Pyrogram v1.0.1, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/app/.heroku/python/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/bot/__main__.py", line 35, in <module>
    app.run()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/methods/utilities/run.py", line 61, in run
    self.start()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
    await self.initialize()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
    self.load_plugins()
  File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/client.py", line 717, in load_plugins
    module = import_module(module_path)
  File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/bot/plugins/authorize.py", line 11, in <module>
    from bot.helpers.sql_helper import gDriveDB
  File "/app/bot/helpers/sql_helper/__init__.py", line 19, in <module>
    SESSION = start()
  File "/app/bot/helpers/sql_helper/__init__.py", line 9, in start
    engine = create_engine(DATABASE_URL)
  File "<string>", line 2, in create_engine
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint
    cls = registry.load(name)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 342, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

[gupload-niraj-console-1616150315198.txt](https://github.com/viperadnan-git/google-drive-telegram-bot/files/6170484/gupload-niraj-console-1616150315198.txt)

**Comment by winkxx** [comment]
I also have the same situation

**Comment by Rocky2242** [comment]
Got it... Resolved ...Now successfuly deployed on heroku...  Telegram--> @darth_vader44

**Comment by Lucifer7535** [comment]
you can fix this error by simply changing the text in requirements.txt

"sqlalchemy"
change it to "
sqlalchemy==1.3.23"

because of 1.4.0 version update it was causing this problem
