### ISSUE TITLE
Error in Heroku Deployment

### ISSUE THREAD

**Issue by BlackBox-cmd** [viperadnan-git/google-drive-telegram-bot#63]
i am unable to  run in  heroku ,heroku logs
Application Logs

2021-04-01T18:03:47.314089+00:00 app[worker.1]:     return fn(*args, **kwargs)

2021-04-01T18:03:47.314090+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine

2021-04-01T18:03:47.314430+00:00 app[worker.1]:     entrypoint = u._get_entrypoint()

2021-04-01T18:03:47.314431+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint

2021-04-01T18:03:47.314900+00:00 app[worker.1]:     cls = registry.load(name)

2021-04-01T18:03:47.314901+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 340, in load

2021-04-01T18:03:47.315268+00:00 app[worker.1]:     "Can't load plugin: %s:%s" % (self.group, name)

2021-04-01T18:03:47.315320+00:00 app[worker.1]: sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

2021-04-01T18:03:47.578468+00:00 heroku[worker.1]: Process exited with status 1

2021-04-01T18:03:47.672609+00:00 heroku[worker.1]: State changed from up to crashed

2021-04-01T18:04:52.227121+00:00 heroku[worker.1]: State changed from crashed to starting

2021-04-01T18:04:57.810003+00:00 heroku[worker.1]: Starting process with command `python -m bot`

2021-04-01T18:04:58.565587+00:00 heroku[worker.1]: State changed from starting to up

2021-04-01T18:05:01.138453+00:00 app[worker.1]: 2021-04-01 18:05:01,138 - __main__ - INFO - Starting Bot !

2021-04-01T18:05:03.476902+00:00 app[worker.1]: Pyrogram v1.0.1, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>

2021-04-01T18:05:03.476978+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

2021-04-01T18:05:03.476979+00:00 app[worker.1]: 

2021-04-01T18:05:08.575962+00:00 app[worker.1]: Traceback (most recent call last):

2021-04-01T18:05:08.576063+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/runpy.py", line 193, in _run_module_as_main

2021-04-01T18:05:08.576476+00:00 app[worker.1]:     "__main__", mod_spec)

2021-04-01T18:05:08.576558+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/runpy.py", line 85, in _run_code

2021-04-01T18:05:08.576828+00:00 app[worker.1]:     exec(code, run_globals)

2021-04-01T18:05:08.576834+00:00 app[worker.1]:   File "/app/bot/__main__.py", line 35, in <module>

2021-04-01T18:05:08.577036+00:00 app[worker.1]:     app.run()

2021-04-01T18:05:08.577041+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/methods/utilities/run.py", line 61, in run

2021-04-01T18:05:08.577277+00:00 app[worker.1]:     self.start()

2021-04-01T18:05:08.577282+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap

2021-04-01T18:05:08.577506+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)

2021-04-01T18:05:08.577511+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete

2021-04-01T18:05:08.577949+00:00 app[worker.1]:     return future.result()

2021-04-01T18:05:08.577954+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/methods/utilities/start.py", line 68, in start

2021-04-01T18:05:08.578182+00:00 app[worker.1]:     await self.initialize()

2021-04-01T18:05:08.578187+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize

2021-04-01T18:05:08.578407+00:00 app[worker.1]:     self.load_plugins()

2021-04-01T18:05:08.578447+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pyrogram/client.py", line 717, in load_plugins

2021-04-01T18:05:08.579101+00:00 app[worker.1]:     module = import_module(module_path)

2021-04-01T18:05:08.579142+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module

2021-04-01T18:05:08.579395+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)

2021-04-01T18:05:08.579433+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import

2021-04-01T18:05:08.579707+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load

2021-04-01T18:05:08.579911+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

2021-04-01T18:05:08.580114+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

2021-04-01T18:05:08.580323+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module

2021-04-01T18:05:08.580551+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

2021-04-01T18:05:08.580764+00:00 app[worker.1]:   File "/app/bot/plugins/authorize.py", line 11, in <module>

2021-04-01T18:05:08.580952+00:00 app[worker.1]:     from bot.helpers.sql_helper import gDriveDB

2021-04-01T18:05:08.580958+00:00 app[worker.1]:   File "/app/bot/helpers/sql_helper/__init__.py", line 19, in <module>

2021-04-01T18:05:08.581174+00:00 app[worker.1]:     SESSION = start()

2021-04-01T18:05:08.581213+00:00 app[worker.1]:   File "/app/bot/helpers/sql_helper/__init__.py", line 9, in start

2021-04-01T18:05:08.581393+00:00 app[worker.1]:     engine = create_engine(DATABASE_URL)

2021-04-01T18:05:08.581429+00:00 app[worker.1]:   File "<string>", line 2, in create_engine

2021-04-01T18:05:08.581658+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned

2021-04-01T18:05:08.582029+00:00 app[worker.1]:     return fn(*args, **kwargs)

2021-04-01T18:05:08.582068+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine

2021-04-01T18:05:08.582569+00:00 app[worker.1]:     entrypoint = u._get_entrypoint()

2021-04-01T18:05:08.582607+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 653, in _get_entrypoint

2021-04-01T18:05:08.583196+00:00 app[worker.1]:     cls = registry.load(name)

2021-04-01T18:05:08.583235+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 340, in load

2021-04-01T18:05:08.583646+00:00 app[worker.1]:     "Can't load plugin: %s:%s" % (self.group, name)

2021-04-01T18:05:08.583726+00:00 app[worker.1]: sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

2021-04-01T18:05:08.808375+00:00 heroku[worker.1]: Process exited with status 1

2021-04-01T18:05:08.893736+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by Lucifer7535** [comment]
you can fix this error by simply changing the text in requirements.txt

"sqlalchemy"
change it to "
sqlalchemy==1.3.23"

because of 1.4.0 version update it was causing this problem

**Comment by BlackBox-cmd** [comment]
> 
> 
> you can fix this error by simply changing the text in requirements.txt
> 
> "sqlalchemy"
> change it to "
> sqlalchemy==1.3.23"
> 
> because of 1.4.0 version update it was causing this problem

Thank You Bro .Now it's Working....
