### ISSUE TITLE
Issue when i tried to run the bot

### ISSUE THREAD

**Issue by Obada8** [viperadnan-git/google-drive-telegram-bot#7]
Hi, please can you see why the bot not running for me?

`root@vultr:~/google-drive-telegram-bot# python3 -m bot
2020-10-05 23:54:38,590 - __main__ - INFO - Starting Bot !
Pyrogram v1.0.1, Copyright (C) 2017-2020 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/google-drive-telegram-bot/bot/__main__.py", line 35, in <module>
    app.run()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/utilities/run.py", line 61, in run
    self.start()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/sync.py", line 51, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/utilities/start.py", line 68, in start
    await self.initialize()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
    self.load_plugins()
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 717, in load_plugins
    module = import_module(module_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/google-drive-telegram-bot/bot/plugins/authorize.py", line 11, in <module>
    from bot.helpers.sql_helper import gDriveDB
  File "/root/google-drive-telegram-bot/bot/helpers/sql_helper/__init__.py", line 19, in <module>
    SESSION = start()
  File "/root/google-drive-telegram-bot/bot/helpers/sql_helper/__init__.py", line 9, in start
    engine = create_engine(DATABASE_URL)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'localhost:5432'
root@vultr:~/google-drive-telegram-bot#`

**Comment by viperadnan-git** [comment]
Incorrect `DATABASE_URL` make sure it's on working State.

**Comment by killerlearner** [comment]
> Incorrect `DATABASE_URL` make sure it's on working State.

Hey bro can you please tell how to create database url. I think it created own by heroku so am I need to copy that and paste it in config and deploy by connect. Because I just created my bot but it not working. It shows started in logs but I cant use it neither in bot chat nor in group. I edit auth file in plugines and paste my google client id and secret their and also give valid group link but I can't use. Can you plss help me in solving this. My telegram id is @killerlearner you can pm me their for better help.

**Comment by viperadnan-git** [comment]
> > Incorrect `DATABASE_URL` make sure it's on working State.
> 
> Hey bro can you please tell how to create database url. I think it created own by heroku so am I need to copy that and paste it in config and deploy by connect. Because I just created my bot but it not working. It shows started in logs but I cant use it neither in bot chat nor in group. I edit auth file in plugines and paste my google client id and secret their and also give valid group link but I can't use. Can you plss help me in solving this. My telegram id is @killerlearner you can pm me their for better help. 

Delete your existing heroku App, Go to official repo, click deploy button, Fill details, Deploy !
